#!/usr/bin/env bash
set -euo pipefail
# ============================================================================
# DAY 2: KAFKA SETUP & PROTO COMPILATION
# ============================================================================
# Expectations:
# - Docker daemon running (docker-compose for Kafka+Zookeeper)
# - protoc installed: apt-get install protoc-gen-go protoc-gen-go-grpc
# - Go 1.21+ available
# - Executed AFTER Day 1 (PostgreSQL migrations complete)
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
cd "$SCRIPT_DIR"

NEXUS_ROOT="${NEXUS_ROOT:-.}"
LOG_FILE="${NEXUS_ROOT}/logs/day2-execution.log"
mkdir -p "$(dirname "$LOG_FILE")"

log() {
  local msg="$1"
  echo "[$(date -u +'%Y-%m-%dT%H:%M:%SZ')] $msg" | tee -a "$LOG_FILE"
}

# ============= STEP 1: Start Kafka & Create Topics =============
log "========== DAY 2 STEP 1: Kafka Topics =========="

if ! command -v docker-compose >/dev/null 2>&1; then
  log "ERROR: docker-compose not found. Install Docker and docker-compose."
  exit 1
fi

log "Starting Kafka & Zookeeper (docker-compose)..."
cd "$NEXUS_ROOT"
docker-compose up -d zookeeper kafka || log "WARN: docker-compose already running"
sleep 5

log "Waiting for Kafka broker to be ready..."
for i in {1..30}; do
  if docker-compose exec -T kafka bash -c 'echo "get" | nc -q2 localhost 9092' >/dev/null 2>&1; then
    log "✅ Kafka broker is ready"
    break
  fi
  if [ $i -eq 30 ]; then
    log "ERROR: Kafka broker did not start in time"
    exit 1
  fi
  sleep 1
done

log "Creating Kafka topics..."
docker-compose exec -T kafka kafka-topics --create \
  --topic "nexus.discovery.raw" \
  --partitions 1 \
  --replication-factor 1 \
  --bootstrap-server localhost:9092 \
  --if-not-exists || log "WARN: nexus.discovery.raw already exists"

docker-compose exec -T kafka kafka-topics --create \
  --topic "nexus.discovery.normalized" \
  --partitions 1 \
  --replication-factor 1 \
  --bootstrap-server localhost:9092 \
  --if-not-exists || log "WARN: nexus.discovery.normalized already exists"

log "✅ Kafka topics created"

# ============= STEP 2: Compile Protos =============
log "========== DAY 2 STEP 2: Proto Compilation =========="

if ! command -v protoc >/dev/null 2>&1; then
  log "ERROR: protoc not found. Install: apt-get install protoc-gen-go protoc-gen-go-grpc"
  exit 1
fi

cd "$NEXUS_ROOT"
if ! command -v protoc-gen-go >/dev/null 2>&1; then
  log "Installing protoc-gen-go..."
  go install github.com/golang/protobuf/protoc-gen-go@latest || true
fi

log "Compiling protos with protoc..."
protoc --go_out=. --go_opt=paths=source_relative \
  proto/discovery.proto || {
  log "ERROR: protoc compilation failed"
  exit 1
}

log "✅ Protos compiled to pkg/discovery/*.pb.go"

# ============= STEP 3: Replace Temp Stub with Generated Code =============
log "========== DAY 2 STEP 3: Replace Stub with Generated Code =========="

if [ -f "pkg/discovery/discovery.pb.go" ]; then
  log "Generated discovery.pb.go found"
  if [ -f "pkg/discovery/discovery.go" ]; then
    log "Removing temporary stub pkg/discovery/discovery.go..."
    rm "pkg/discovery/discovery.go"
  fi
  log "✅ Generated proto code in place"
else
  log "ERROR: discovery.pb.go not generated by protoc"
  exit 1
fi

# ============= STEP 4: Build & Test =============
log "========== DAY 2 STEP 4: Build & Tests =========="

log "Running go mod tidy..."
go mod tidy || log "WARN: go mod tidy had issues"

log "Building ingestion binary..."
go build -o bin/ingestion ./cmd/ingestion || {
  log "ERROR: go build failed"
  exit 1
}
log "✅ Binary built: bin/ingestion"

log "Running Go tests..."
go test ./... -v 2>&1 | tee -a "$LOG_FILE" || {
  log "WARN: Tests had failures (see log)"
}

# ============= STEP 5: Verify Producer/Consumer =============
log "========== DAY 2 STEP 5: Producer/Consumer Verification =========="

log "Verifying Kafka connectivity..."
go run ./cmd/ingestion -test_kafka_only 2>&1 | tee -a "$LOG_FILE" || \
  log "WARN: Producer/consumer test skipped or failed"

# ============= SUMMARY =============
log "========== DAY 2 COMPLETE =========="
log "✅ Kafka topics: nexus.discovery.raw, nexus.discovery.normalized"
log "✅ Protos compiled (pkg/discovery/*.pb.go)"
log "✅ Temporary stub replaced with generated code"
log "✅ Build successful: bin/ingestion"
log "✅ Tests executed"
log "✅ Log: $LOG_FILE"
log ""
log "Next: Deploy to Cloud Run"
log "  IMAGE=gcr.io/my-project/nexus-ingestion TAG=2026-03-12"
log "  ./scripts/deploy_direct.sh"

exit 0
