#!/usr/bin/env bash
set -euo pipefail

# Deployment provisioning automation
# - Generates deployment artifacts (summary, PR/CI lists)
# - Creates or updates a GitHub issue titled "Deployment Summary - <date>"
# - Idempotent: updates the same issue when re-run

WORKDIR=$(pwd)
OUTDIR="$WORKDIR/artifacts"
mkdir -p "$OUTDIR"

NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
BRANCH=$(git rev-parse --abbrev-ref HEAD || echo main)
SHA=$(git rev-parse --short HEAD || echo unknown)

SUMMARY_FILE="$OUTDIR/deployment_summary_${SHA}.md"

cat > "$SUMMARY_FILE" <<EOF
# Deployment Summary

- Date (UTC): $NOW
- Branch: $BRANCH
- Commit: $SHA

## Recent Merges

EOF

# List recent merged PRs (from git merge commits) - last 50
git log --merges --pretty=format:"- %h %s" -n 50 >> "$SUMMARY_FILE" || true

echo "\n## Open PRs" >> "$SUMMARY_FILE"
gh pr list --repo "$GITHUB_REPOSITORY" --state open --limit 100 --json number,title,url,headRefName,mergeable --jq -r '.[] | "- #\(.number) [\(.title)](\(.url)) (head: \(.headRefName)) mergeable:\(.mergeable)"' >> "$SUMMARY_FILE" || true

echo "\n## Recent Workflow Runs" >> "$SUMMARY_FILE"
gh run list --repo "$GITHUB_REPOSITORY" --limit 20 --json workflow,name,conclusion,url,createdAt --jq -r '.[] | "- [\(.workflow.name)](\(.url)) - \(.conclusion) - \(.createdAt)"' >> "$SUMMARY_FILE" || true

echo "\n## Notes" >> "$SUMMARY_FILE"
echo "Generated by deployment automation script." >> "$SUMMARY_FILE"

echo "Created summary at $SUMMARY_FILE"

# Create or update an issue for the deployment summary
ISSUE_TITLE="Deployment Summary - $NOW"

# Try to find if an existing summary issue for this branch/day exists (simple heuristic: title contains 'Deployment Summary -')
EXISTING=$(gh issue list --repo "$GITHUB_REPOSITORY" --search "Deployment Summary -" --limit 50 --json number,title --jq '.[] | .number' || true)

if [ -n "$EXISTING" ]; then
  # Update the most recent matching issue
  ISSUE_NUMBER=$(echo "$EXISTING" | head -n1)
  gh issue comment "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --body-file "$SUMMARY_FILE" || true
  gh issue edit "$ISSUE_NUMBER" --repo "$GITHUB_REPOSITORY" --title "$ISSUE_TITLE" || true
  echo "Updated issue #$ISSUE_NUMBER with deployment summary"
else
  NEW=$(gh issue create --repo "$GITHUB_REPOSITORY" --title "$ISSUE_TITLE" --body-file "$SUMMARY_FILE" --label "deployment" || true)
  echo "Created new deployment issue: $NEW"
fi

exit 0
