#!/bin/bash

# QUICK START - Cost Management for Development

echo "═══════════════════════════════════════════════════════════"
echo "🚀 Cost Management Quick Start"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "This guide shows how to enable/use the 5-minute idle cleanup system."
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}STEP 1: Initialize Cost Management${NC}"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Run the setup script once:"
echo -e "${BLUE}  bash scripts/cost-management/setup.sh${NC}"
echo ""
echo "This will:"
echo "  ✓ Verify all scripts are in place"
echo "  ✓ Set file permissions"
echo "  ✓ Install systemd unit files (when possible)"
echo "  ✓ Generate initial cost estimate"
echo ""

echo -e "${YELLOW}STEP 2: Deploy to Git${NC}"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Commit all changes:"
echo -e "${BLUE}  git add -A${NC}"
echo -e "${BLUE}  git commit -m \"feat: enable cost-management 5-min idle cleanup\"${NC}"
echo -e "${BLUE}  git push${NC}"
echo ""

echo -e "${YELLOW}STEP 3: Install & enable systemd units${NC}"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Copy unit files and enable timer (requires sudo):"
echo -e "  sudo cp systemd/*.service systemd/*.timer /etc/systemd/system/ && sudo systemctl daemon-reload && sudo systemctl enable --now idle-cleanup.timer"
echo ""

echo -e "${YELLOW}STEP 4: Place GCP credentials on host${NC}"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Place service account JSON securely on host and set environment variable:"
echo ""
echo "  sudo mkdir -p /etc/nexusshield && sudo mv /path/to/service-account-key.json /etc/nexusshield/gcp-sa.json && sudo chmod 640 /etc/nexusshield/gcp-sa.json"
echo "  export GOOGLE_APPLICATION_CREDENTIALS=/etc/nexusshield/gcp-sa.json"
echo ""

echo -e "${YELLOW}STEP 5: Test Cleanup (Manual)${NC}"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Verify cleanup works:"
echo -e "${BLUE}  bash scripts/cost-management/idle-resource-cleanup.sh${NC}"
echo ""
echo "Check logs:"
echo -e "${BLUE}  tail -f logs/cost-management/cleanup-*.log${NC}"
echo ""

echo -e "${YELLOW}STEP 6: Test Activation (Manual)${NC}"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Wake up resources on-demand:"
echo -e "${BLUE}  bash scripts/cost-management/on-demand-activation.sh${NC}"
echo ""
echo "Check logs:"
echo -e "${BLUE}  tail -f logs/cost-management/activation-*.log${NC}"
echo ""

echo -e "${YELLOW}STEP 7: Monitor Savings${NC}"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Generate cost report:"
echo -e "${BLUE}  bash scripts/cost-management/cost-estimation.sh${NC}"
echo ""
echo "Check GCP billing:"
echo -e "${BLUE}  gcloud billing accounts list${NC}"
echo ""

echo -e "${YELLOW}STEP 8: Daily Use${NC}"
echo "────────────────────────────────────────────────────────"
echo ""
echo "Typical development workflow:"
echo ""
echo "  Morning (start work):"
echo -e "    ${BLUE}bash scripts/cost-management/on-demand-activation.sh${NC}"
echo "    (or sudo systemctl start on-demand-activation.service)"
echo ""
echo "  Work on features (5 min idle → auto-cleanup)"
echo ""
echo "  End of day:"
echo "    (resources auto-cleanup, zero idle costs)"
echo ""

echo ""
echo -e "${GREEN}═══════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ SETUP COMPLETE!${NC}"
echo ""
echo "Key Points:"
echo "  • Cleanup runs every 5 minutes (systemd timer)"
echo "  • Resources scale to zero automatically"
echo "  • Activate on-demand: 1 command or systemd service start"
echo "  • Expected savings: 70-80% monthly (~$110-200)"
echo ""
echo "For detailed info:"
echo -e "  ${BLUE}cat COST_MANAGEMENT_GUIDE.md${NC}"
echo ""
echo "Current status:"
echo -e "  ${BLUE}cat COST_MANAGEMENT_DEPLOYMENT_STATUS.md${NC}"
echo ""
echo "═══════════════════════════════════════════════════════════"
