apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gsm-database-secrets
  namespace: cron-jobs
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/milestone-organizer-db-password/versions/latest"
        path: "db-password"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/milestone-organizer-db-username/versions/latest"
        path: "db-username"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/milestone-organizer-api-key/versions/latest"
        path: "api-key"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/milestone-organizer-s3-access-key/versions/latest"
        path: "s3-access-key"
      - resourceName: "projects/${GCP_PROJECT_ID}/secrets/milestone-organizer-s3-secret-key/versions/latest"
        path: "s3-secret-key"
  secretObjects:
  - secretKey: db-password
    objectName: db-password
  - secretKey: db-username
    objectName: db-username
  - secretKey: api-key
    objectName: api-key
  - secretKey: s3-access-key
    objectName: s3-access-key
  - secretKey: s3-secret-key
    objectName: s3-secret-key
