#!/usr/bin/env bash
# Helper to prepare cloud credential env file for tests
# Usage: ./prepare-creds.sh --output tests/cloud-creds.env

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_FILE="${SCRIPT_DIR}/cloud-creds.env"
GCP_SA_FILE="${SCRIPT_DIR}/gcp-sa.json"
AZURE_CREDS_FILE="${SCRIPT_DIR}/azure-credentials.json"

show_help() {
  cat <<EOF
prepare-creds.sh - Prepare cloud credentials env file for tests

By default this script will create ${OUT_FILE} from environment variables.
It will refuse to write if required values are missing; use --force to write
an incomplete file (not recommended).

Options:
  --output PATH   Write creds to PATH (default: ${OUT_FILE})
  --force         Write file even if required vars are missing
  --help          Show this help

Example:
  # From CI/web portal that injects secrets into env
  ./prepare-creds.sh

  # Or set env vars locally then run
  AWS_REGION=us-east-1 GCP_PROJECT=my-project GITHUB_TOKEN=ghr_xxx ./prepare-creds.sh

EOF
}

force_write=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --output)
      OUT_FILE="$2"
      shift 2
      ;;
    --force)
      force_write=true
      shift
      ;;
    --help|-h)
      show_help
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      show_help
      exit 2
      ;;
  esac
done

# Collect values from environment
cat > /tmp/creds_check.$$ <<EOF
AWS_REGION=${AWS_REGION:-}
AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
GCP_PROJECT=${GCP_PROJECT:-}
GCP_SA_KEY=${GCP_SA_KEY:-}
GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-}
AZURE_SUBSCRIPTION=${AZURE_SUBSCRIPTION:-}
AZURE_CLIENT_ID=${AZURE_CLIENT_ID:-}
AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET:-}
AZURE_TENANT_ID=${AZURE_TENANT_ID:-}
AZURE_CREDENTIALS=${AZURE_CREDENTIALS:-}
GITHUB_TOKEN=${GITHUB_TOKEN:-}
EOF

missing_count=0
while IFS="=" read -r k v; do
  if [[ "${v}" == "" ]]; then
    case "$k" in
      AWS_REGION|GCP_PROJECT|AZURE_SUBSCRIPTION|GITHUB_TOKEN)
        echo "[MISSING] $k"
        missing_count=$((missing_count+1))
        ;;
      *)
        # optional
        ;;
    esac
  fi
done < /tmp/creds_check.$$

rm -f /tmp/creds_check.$$

if [[ ${missing_count} -gt 0 && "${force_write}" == "false" ]]; then
  echo ""
  echo "${missing_count} required variables are missing."
  echo "Set required env vars or provide values in the web portal and re-run this script, or pass --force to write an incomplete file."
  exit 3
fi

# Write output file
# If GCP service-account key provided directly via GCP_SA_KEY (raw JSON or base64), write it to a file and set GOOGLE_APPLICATION_CREDENTIALS
if [[ -n "${GCP_SA_KEY:-}" ]]; then
  # Detect base64 vs raw JSON
  if echo "${GCP_SA_KEY}" | jq -e . >/dev/null 2>&1; then
    echo "Writing GCP service account JSON to ${GCP_SA_FILE}"
    printf '%s' "${GCP_SA_KEY}" > "${GCP_SA_FILE}"
  else
    # try base64 decode
    if echo "${GCP_SA_KEY}" | base64 --decode >/dev/null 2>&1; then
      echo "Decoding base64 GCP_SA_KEY to ${GCP_SA_FILE}"
      echo "${GCP_SA_KEY}" | base64 --decode > "${GCP_SA_FILE}"
    else
      echo "Warning: GCP_SA_KEY provided but not valid JSON or base64; skipping" >&2
    fi
  fi
  export GOOGLE_APPLICATION_CREDENTIALS="${GCP_SA_FILE}"
fi

if [[ -n "${AZURE_CREDENTIALS:-}" ]]; then
  # AZURE_CREDENTIALS expected to be a JSON string containing clientId, clientSecret, tenantId, subscriptionId
  echo "Writing Azure credentials to ${AZURE_CREDS_FILE}"
  printf '%s' "${AZURE_CREDENTIALS}" > "${AZURE_CREDS_FILE}"
  # Try to extract fields using jq if available
  if command -v jq >/dev/null 2>&1; then
    AZURE_CLIENT_ID=$(jq -r '.clientId // empty' "${AZURE_CREDS_FILE}")
    AZURE_CLIENT_SECRET=$(jq -r '.clientSecret // empty' "${AZURE_CREDS_FILE}")
    AZURE_TENANT_ID=$(jq -r '.tenantId // empty' "${AZURE_CREDS_FILE}")
    AZURE_SUBSCRIPTION=$(jq -r '.subscriptionId // empty' "${AZURE_CREDS_FILE}")
  fi
fi

cat > "${OUT_FILE}" <<EOF
# Auto-generated by prepare-creds.sh on $(date -Iseconds)
# WARNING: keep this file secret and add to .gitignore if created locally

AWS_REGION="${AWS_REGION:-}"
AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-}"
AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-}"

GCP_PROJECT="${GCP_PROJECT:-}"
GOOGLE_APPLICATION_CREDENTIALS="${GOOGLE_APPLICATION_CREDENTIALS:-${GCP_SA_FILE}}"

AZURE_SUBSCRIPTION="${AZURE_SUBSCRIPTION:-}"
AZURE_CLIENT_ID="${AZURE_CLIENT_ID:-}"
AZURE_CLIENT_SECRET="${AZURE_CLIENT_SECRET:-}"
AZURE_TENANT_ID="${AZURE_TENANT_ID:-}"

GITHUB_TOKEN="${GITHUB_TOKEN:-}"
EOF

chmod 600 "${OUT_FILE}"

# Ensure script is executable by owner so CI/web portal can run it directly
chmod 700 "${BASH_SOURCE[0]}" || true

echo "Wrote credentials to ${OUT_FILE} (owner-only permissions 600)."

echo "Next steps:"
echo "  - Confirm file contents are correct: ls -l ${OUT_FILE}"
echo "  - Run cloud tests, e.g. AWS_REGION=us-east-1 ./run-tests.sh --with-ec2"

exit 0
