#!/usr/bin/env python3
#
# 🤖 AUTOMATED ISSUE MANAGER
#
# Creates, updates, and closes GitHub issues automatically
# Tracks deployments with immutable audit trail
#
# Usage:
#   python3 issue-manager.py --create-deployment COMMIT_SHA
#   python3 issue-manager.py --update-deployment ISSUE_ID STATUS MESSAGE
#   python3 issue-manager.py --close-deployment ISSUE_ID SUCCESS

import os
import sys
import json
import subprocess
from datetime import datetime
from typing import Optional, Dict, Any
import tempfile

try:
    import requests
except ImportError:
    print("ERROR: requests module required. Install with: pip3 install requests")
    sys.exit(1)

# ============================================================================
# CONFIGURATION
# ============================================================================

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_OWNER = os.environ.get("GITHUB_OWNER", "kushin77")
GITHUB_REPO = os.environ.get("GITHUB_REPO", "self-hosted-runner")
API_BASE = "https://api.github.com"
AUDIT_LOG = "/data/audit/github-issues.jsonl"

# ============================================================================
# GITHUB API WRAPPER
# ============================================================================

class GitHubAPI:
    def __init__(self, token: str, owner: str, repo: str):
        self.token = token
        self.owner = owner
        self.repo = repo
        self.headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json"
        }
    
    def create_issue(self, title: str, body: str, labels: list = None) -> Dict[str, Any]:
        """Create a new GitHub issue"""
        url = f"{API_BASE}/repos/{self.owner}/{self.repo}/issues"
        
        data = {
            "title": title,
            "body": body,
            "labels": labels or []
        }
        
        response = requests.post(url, json=data, headers=self.headers)
        
        if response.status_code != 201:
            raise Exception(f"Failed to create issue: {response.text}")
        
        return response.json()
    
    def update_issue(self, issue_number: int, state: str = None, body: str = None) -> Dict[str, Any]:
        """Update a GitHub issue"""
        url = f"{API_BASE}/repos/{self.owner}/{self.repo}/issues/{issue_number}"
        
        data = {}
        if state:
            data["state"] = state
        if body:
            data["body"] = body
        
        response = requests.patch(url, json=data, headers=self.headers)
        
        if response.status_code != 200:
            raise Exception(f"Failed to update issue: {response.text}")
        
        return response.json()
    
    def add_comment(self, issue_number: int, body: str) -> Dict[str, Any]:
        """Add a comment to an issue"""
        url = f"{API_BASE}/repos/{self.owner}/{self.repo}/issues/{issue_number}/comments"
        
        data = {"body": body}
        
        response = requests.post(url, json=data, headers=self.headers)
        
        if response.status_code != 201:
            raise Exception(f"Failed to add comment: {response.text}")
        
        return response.json()

# ============================================================================
# ISSUE MANAGEMENT
# ============================================================================

def get_deployment_issue_body(commit_sha: str, status: str = "pending") -> str:
    """Generate issue body for deployment tracking"""
    
    # Get commit info
    try:
        commit_info = subprocess.check_output(
            ["git", "log", "-1", "--pretty=%B", commit_sha],
            text=True
        ).strip()
    except:
        commit_info = "(commit info unavailable)"
    
    body = f"""
## Deployment Tracking Issue

**Status**: {status}
**Commit**: `{commit_sha[:8]}`
**Triggered**: {datetime.utcnow().isoformat()}Z
**Target**: on-prem worker node (192.168.168.42)

### Commit Message
```
{commit_info}
```

### Deployment Pipeline
- [ ] Git validation
- [ ] NAS sync
- [ ] Deployment validation
- [ ] Execution
- [ ] Health check
- [ ] Audit finalization

### Logs
> To be updated as deployment progresses

---
*Auto-generated by Deployment Automation System*
*Never manually close - closure will be automated*
"""
    return body

def create_deployment_issue(commit_sha: str) -> int:
    """Create a new deployment tracking issue"""
    
    try:
        # Truncate SHA for title
        short_sha = commit_sha[:8]
        title = f"🚀 Deployment: {short_sha}"
        
        body = get_deployment_issue_body(commit_sha, "pending")
        
        gh = GitHubAPI(GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO)
        issue = gh.create_issue(title, body, labels=["deployment", "auto-generated"])
        
        issue_number = issue["number"]
        
        # Audit log
        audit_event({
            "event": "issue_created",
            "issue_number": issue_number,
            "commit": commit_sha,
            "status": "success"
        })
        
        print(f"✅ Created deployment issue: #{issue_number}")
        return issue_number
        
    except Exception as e:
        print(f"❌ Error creating deployment issue: {e}")
        audit_event({
            "event": "issue_created",
            "commit": commit_sha,
            "status": "failed",
            "error": str(e)
        })
        return -1

def update_deployment_issue(issue_number: int, status: str, logs: str) -> bool:
    """Update deployment issue with progress"""
    
    try:
        gh = GitHubAPI(GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO)
        
        comment = f"""
## Deployment Progress Update

**Status**: {status}
**Updated**: {datetime.utcnow().isoformat()}Z

### Recent Logs
```
{logs}
```
"""
        
        gh.add_comment(issue_number, comment)
        
        audit_event({
            "event": "issue_updated",
            "issue_number": issue_number,
            "status": status
        })
        
        print(f"✅ Updated deployment issue: #{issue_number}")
        return True
        
    except Exception as e:
        print(f"❌ Error updating deployment issue: {e}")
        audit_event({
            "event": "issue_update_failed",
            "issue_number": issue_number,
            "error": str(e)
        })
        return False

def close_deployment_issue(issue_number: int, success: bool, summary: str) -> bool:
    """Close deployment issue after completion"""
    
    try:
        gh = GitHubAPI(GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO)
        
        if success:
            gh.update_issue(issue_number, state="closed")
            final_comment = f"""
## ✅ Deployment Successful

**Completion Time**: {datetime.utcnow().isoformat()}Z

### Summary
{summary}

---
Deployment completed and verified. Issue auto-closed by deployment system.
"""
        else:
            final_comment = f"""
## ❌ Deployment Failed

**Failure Time**: {datetime.utcnow().isoformat()}Z

### Summary
{summary}

---
Deployment failed. Automatic rollback initiated. Manual review may be required.
"""
            # Don't auto-close on failure
        
        gh.add_comment(issue_number, final_comment)
        
        audit_event({
            "event": "issue_closed",
            "issue_number": issue_number,
            "success": success
        })
        
        if success:
            print(f"✅ Closed deployment issue: #{issue_number}")
        else:
            print(f"⚠️  Deployment failed - issue #{issue_number} left open for review")
        return True
        
    except Exception as e:
        print(f"❌ Error closing deployment issue: {e}")
        audit_event({
            "event": "issue_close_failed",
            "issue_number": issue_number,
            "error": str(e)
        })
        return False

# ============================================================================
# AUDIT TRAIL
# ============================================================================

def audit_event(event: Dict[str, Any]) -> None:
    """Log event to immutable audit trail"""
    
    try:
        os.makedirs(os.path.dirname(AUDIT_LOG), exist_ok=True)
        
        event["timestamp"] = datetime.utcnow().isoformat() + "Z"
        
        with open(AUDIT_LOG, "a") as f:
            f.write(json.dumps(event) + "\n")
        
        # Make audit log append-only
        os.chmod(AUDIT_LOG, 0o444)
        
    except Exception as e:
        print(f"⚠️  Failed to write audit log: {e}", file=sys.stderr)

# ============================================================================
# CLI
# ============================================================================

def main():
    if len(sys.argv) < 2:
        print("Usage:")
        print("  python3 issue-manager.py --create-deployment COMMIT_SHA")
        print("  python3 issue-manager.py --update-deployment ISSUE_ID STATUS LOGS")
        print("  python3 issue-manager.py --close-deployment ISSUE_ID SUCCESS SUMMARY")
        sys.exit(1)
    
    command = sys.argv[1]
    
    if command == "--create-deployment" and len(sys.argv) >= 3:
        commit_sha = sys.argv[2]
        issue_id = create_deployment_issue(commit_sha)
        print(issue_id)
        sys.exit(0 if issue_id > 0 else 1)
    
    elif command == "--update-deployment" and len(sys.argv) >= 5:
        issue_id = int(sys.argv[2])
        status = sys.argv[3]
        logs = sys.argv[4]
        success = update_deployment_issue(issue_id, status, logs)
        sys.exit(0 if success else 1)
    
    elif command == "--close-deployment" and len(sys.argv) >= 5:
        issue_id = int(sys.argv[2])
        success = sys.argv[3].lower() == "true"
        summary = sys.argv[4]
        result = close_deployment_issue(issue_id, success, summary)
        sys.exit(0 if result else 1)
    
    else:
        print("ERROR: Invalid command or arguments")
        sys.exit(1)

if __name__ == "__main__":
    main()
