"""Alerting module for sending notifications on orchestration events."""
import json
import logging
import os
import time
from typing import Optional, Dict, Any
from enum import Enum

logger = logging.getLogger(__name__)

try:
    import requests
    HAS_REQUESTS = True
except ImportError:
    HAS_REQUESTS = False


class AlertSeverity(Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertManager:
    """Manages alert delivery to multiple channels (Slack, GitHub, PagerDuty)."""

    def __init__(self):
        self.channels = []

    def add_slack_channel(self, webhook_url: Optional[str] = None):
        """Add Slack as an alert channel."""
        url = webhook_url or os.environ.get("SLACK_WEBHOOK_URL")
        if url:
            self.channels.append(("slack", url))

    def add_github_channel(self, owner: str, repo: str, token: Optional[str] = None):
        """Add GitHub issues as an alert channel."""
        token = token or os.environ.get("GITHUB_TOKEN")
        if token:
            self.channels.append(("github", {"owner": owner, "repo": repo, "token": token}))

    def add_pagerduty_channel(self, integration_key: Optional[str] = None):
        """Add PagerDuty as an alert channel."""
        key = integration_key or os.environ.get("PAGERDUTY_INTEGRATION_KEY")
        if key:
            self.channels.append(("pagerduty", key))

    def send_alert(self, title: str, message: str, severity: AlertSeverity = AlertSeverity.WARNING,
                   metadata: Optional[Dict[str, Any]] = None):
        """Send an alert to all configured channels."""
        metadata = metadata or {}
        
        for channel_type, config in self.channels:
            try:
                if channel_type == "slack":
                    self._send_slack(title, message, severity, metadata, config)
                elif channel_type == "github":
                    self._send_github_issue(title, message, severity, metadata, config)
                elif channel_type == "pagerduty":
                    self._send_pagerduty(title, message, severity, metadata, config)
            except Exception as e:
                logger.exception("Failed to send alert to %s: %s", channel_type, e)

    def _send_slack(self, title: str, message: str, severity: AlertSeverity,
                    metadata: Dict[str, Any], webhook_url: str):
        """Send alert to Slack."""
        if not HAS_REQUESTS:
            logger.warning("requests not available; Slack alert skipped")
            return

        color_map = {
            AlertSeverity.INFO: "#0099ff",
            AlertSeverity.WARNING: "#ffaa00",
            AlertSeverity.CRITICAL: "#ff0000",
        }
        
        payload = {
            "attachments": [
                {
                    "title": title,
                    "text": message,
                    "color": color_map.get(severity, "#999999"),
                    "fields": [{"title": k, "value": str(v), "short": True} for k, v in metadata.items()],
                    "footer": "self-healing-orchestrator",
                    "ts": int(time.time()),
                }
            ]
        }
        
        resp = requests.post(webhook_url, json=payload, timeout=10)
        resp.raise_for_status()
        logger.info("Slack alert sent: %s", title)

    def _send_github_issue(self, title: str, message: str, severity: AlertSeverity,
                          metadata: Dict[str, Any], config: Dict[str, str]):
        """Create a GitHub issue for the alert."""
        if not HAS_REQUESTS:
            logger.warning("requests not available; GitHub alert skipped")
            return

        owner = config["owner"]
        repo = config["repo"]
        token = config["token"]

        body = f"""## Alert: {severity.value.upper()}

{message}

### Metadata
```json
{json.dumps(metadata, indent=2)}
```

---
*Generated by self-healing-orchestrator*
"""

        url = f"https://api.github.com/repos/{owner}/{repo}/issues"
        headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
        }
        payload = {
            "title": f"[{severity.value.upper()}] {title}",
            "body": body,
            "labels": ["alert", "automated", severity.value],
        }

        resp = requests.post(url, json=payload, headers=headers, timeout=10)
        resp.raise_for_status()
        logger.info("GitHub issue created for alert: %s", title)

    def _send_pagerduty(self, title: str, message: str, severity: AlertSeverity,
                       metadata: Dict[str, Any], integration_key: str):
        """Send alert to PagerDuty."""
        if not HAS_REQUESTS:
            logger.warning("requests not available; PagerDuty alert skipped")
            return

        severity_map = {
            AlertSeverity.INFO: "info",
            AlertSeverity.WARNING: "warning",
            AlertSeverity.CRITICAL: "critical",
        }

        payload = {
            "routing_key": integration_key,
            "event_action": "trigger",
            "dedup_key": f"orchestrator-{title}",
            "payload": {
                "summary": title,
                "severity": severity_map.get(severity, "warning"),
                "source": "self-healing-orchestrator",
                "custom_details": metadata,
            },
        }

        resp = requests.post(
            "https://events.pagerduty.com/v2/enqueue",
            json=payload,
            timeout=10
        )
        resp.raise_for_status()
        logger.info("PagerDuty alert sent: %s", title)


class CircuitBreakerMonitor:
    """Monitor circuit breaker state and alert on state changes."""

    def __init__(self, alert_manager: Optional[AlertManager] = None):
        self.alert_manager = alert_manager or AlertManager()
        self.circuit_breaker_states: Dict[str, str] = {}

    def update_state(self, circuit_name: str, new_state: str):
        """Update circuit breaker state and alert on change."""
        old_state = self.circuit_breaker_states.get(circuit_name)
        self.circuit_breaker_states[circuit_name] = new_state

        if old_state != new_state:
            severity = AlertSeverity.CRITICAL if new_state == "open" else AlertSeverity.WARNING
            self.alert_manager.send_alert(
                title=f"Circuit breaker state change: {circuit_name}",
                message=f"Circuit breaker '{circuit_name}' changed from {old_state} to {new_state}",
                severity=severity,
                metadata={"circuit_name": circuit_name, "old_state": old_state, "new_state": new_state}
            )


__all__ = [
    "AlertManager",
    "AlertSeverity",
    "CircuitBreakerMonitor",
]
