apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: milestone-organizer-spc
  namespace: ops
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "github-token"
        objectType: "secretsmanager"
        objectAlias: "gh_token"
      - objectName: "aws-credentials"
        objectType: "secretsmanager"
        objectAlias: "aws_credentials"
  # To create Kubernetes Secrets from provider objects, uncomment and configure secretObjects.
  # secretObjects:
  #   - secretName: github-token
  #     type: Opaque
  #     data:
  #       - objectName: github-token
  #         key: gh_token
