#!/usr/bin/env python3
import json
from pathlib import Path
from collections import defaultdict
import datetime

ROOT = Path(__file__).resolve().parents[2]
LOG_DIR = ROOT / 'logs' / 'stabilization-monitor'
OUT = ROOT / 'reports'
OUT.mkdir(parents=True, exist_ok=True)

def load_events():
    events = []
    for p in sorted(LOG_DIR.glob('stabilization-*.jsonl')):
        for line in p.read_text().splitlines():
            try:
                events.append(json.loads(line))
            except Exception:
                # Attempt to parse legacy stabilization summary lines (non-JSON)
                # Format example contains paths and counts and a recent_failures key.
                try:
                    # extract recent_failures
                    import re
                    m = re.search(r'"recent_failures"\s*:\s*(\d+)', line)
                    if m:
                        events.append({'component': 'stabilization', 'status': 'legacy_summary', 'recent_failures': int(m.group(1))})
                        continue
                    # extract epic file counts like gcp-migration-...jsonl:2
                    parts = re.findall(r'([\w\-]+-migration/[^:\s]+\.jsonl):(\d+)', line)
                    for fp, cnt in parts:
                        # derive component from folder name
                        comp = fp.split('/')[0]
                        events.append({'component': comp, 'status': 'legacy_counts', 'count': int(cnt)})
                        # only a lightweight representation; continue parsing
                except Exception:
                    continue
    return events

def summarize(events):
    by_component = defaultdict(list)
    total = 0
    failures = 0
    for e in events:
        total += 1
        comp = e.get('component','unknown')
        status = e.get('status', 'unknown')
        by_component[comp].append(status)
        if status != 'success':
            failures += 1

    summary = {
        'total_samples': total,
        'total_failures': failures,
        'components': {}
    }
    for comp, statuses in by_component.items():
        succ = sum(1 for s in statuses if s=='success')
        summary['components'][comp] = {
            'samples': len(statuses),
            'success_rate': round(succ / len(statuses) * 100, 2) if statuses else 0.0,
            'failures': [s for s in statuses if s!='success'][:20]
        }
    return summary

def render_md(summary, out_path):
    now = datetime.datetime.utcnow().isoformat() + 'Z'
    lines = []
    lines.append('# Final Stability Report')
    lines.append(f'Generated: {now}')
    lines.append('')
    lines.append(f'- Total samples: {summary["total_samples"]}')
    lines.append(f'- Total failures: {summary["total_failures"]}')
    lines.append('')
    lines.append('## Component Breakdown')
    for comp, info in summary['components'].items():
        lines.append(f'- **{comp}**: {info["samples"]} samples, success_rate={info["success_rate"]}%')
    lines.append('')
    lines.append('## Notes')
    lines.append('- This report is auto-generated by the post-24h analysis job.')
    out_path.write_text('\n'.join(lines))

def main():
    events = load_events()
    if not events:
        print('No stabilization events found')
        return 2
    summary = summarize(events)
    out_path = OUT / f'FINAL_STABILITY_REPORT_{datetime.datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")}.md'
    render_md(summary, out_path)
    print('Wrote', out_path)
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
