version: '3.7'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.79.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    command: ["--config", "/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318" # OTLP HTTP
      - "4317:4317" # OTLP gRPC
      - "8888:8888" # prometheus receiver / admin (if enabled)
    restart: unless-stopped
