apiVersion: batch/v1
kind: CronJob
metadata:
  name: normalizer
  namespace: nexus-engine
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: normalizer
            image: us-central1-docker.pkg.dev/nexusshield-prod/nexus-registry/nexus-normalizer:sha-a96bb48d5
            imagePullPolicy: IfNotPresent