apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor.fullname" . | default (printf "%s-harbor-core" .Release.Name) }}
  labels:
    app: harbor-core
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: harbor-core
  template:
    metadata:
      labels:
        app: harbor-core
    spec:
      containers:
        - name: harbor-core
          image: "{{ .Values.image.core.repository }}:{{ .Values.image.core.tag }}"
          ports:
            - containerPort: 8080
          # Database / external services configuration
          env:
            - name: DATABASE_HOST
              value: "{{ .Values.database.host }}"
            - name: DATABASE_USER
              value: "{{ .Values.database.user }}"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.database.passwordSecret }}"
                  key: "password"

          resources: {{ toYaml .Values.resources | nindent 12 }}
