#!/usr/bin/env bash
set -euo pipefail

# Create/update production hardening milestone and issues.
# Default mode is dry-run. Use --apply for writes.

DRY_RUN=true
REPO="${GH_REPO:-}"
MILESTONE_TITLE="${MILESTONE_TITLE:-Production Hardening and Shutdown Readiness}"

usage() {
  echo "Usage: $0 --repo owner/name [--apply]"
  exit 2
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO="$2"; shift 2 ;;
    --apply) DRY_RUN=false; shift ;;
    -h|--help) usage ;;
    *) usage ;;
  esac
done

[ -n "$REPO" ] || usage

if ! command -v gh >/dev/null 2>&1; then
  echo "gh CLI not found"
  exit 1
fi

declare -a TASKS=(
  "Shutdown all on-prem services and containers"
  "Shutdown GCP/AWS/Azure active workloads"
  "Implement complete cleanup and hibernation checks"
  "Enforce immutable/ephemeral/idempotent automation guarantees"
  "Code-review overlap and remove duplicate automation"
  "Consolidate all testing into one production portal suite"
  "Validate secrets sync across all clouds"
  "Promote repository to production-grade baseline"
  "Validate shutdown and reboot logs"
  "Track and centralize all runtime errors"
  "Design and prioritize 10x enhancement backlog"
  "Validate portal and backend zero-drift synchronization"
  "Finalize commit/push/merge-to-main runbook checks"
  "Track all work in milestones and GitHub issues"
)

echo "Repository: $REPO"
echo "Milestone: $MILESTONE_TITLE"
echo "Mode: $([ "$DRY_RUN" = true ] && echo dry-run || echo apply)"

if [ "$DRY_RUN" = false ]; then
  existing_milestone=$(gh api "repos/${REPO}/milestones" --jq ".[] | select(.title==\"${MILESTONE_TITLE}\") | .number" || true)
  if [ -z "$existing_milestone" ]; then
    gh api "repos/${REPO}/milestones" -f title="$MILESTONE_TITLE" -f state="open" >/dev/null
  fi
fi

for task in "${TASKS[@]}"; do
  title="[Prod Hardening] ${task}"
  body="Automated tracking task generated by scripts/github/track-production-hardening.sh\n\nAcceptance criteria:\n- Implemented\n- Validated\n- Documented"

  if [ "$DRY_RUN" = true ]; then
    echo "DRY-RUN: would create issue: $title"
    continue
  fi

  existing=$(gh issue list --repo "$REPO" --search "$title in:title state:open" --json number --jq '.[0].number' || true)
  if [ -n "$existing" ] && [ "$existing" != "null" ]; then
    echo "Issue already exists: #$existing $title"
    continue
  fi

  gh issue create \
    --repo "$REPO" \
    --title "$title" \
    --body "$body" \
    --milestone "$MILESTONE_TITLE" >/dev/null
  echo "Created issue: $title"
done

echo "Tracking setup complete."
