apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability.fullname" . | default (printf "%s-prometheus" .Release.Name) }}
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          resources: {{ toYaml .Values.prometheus.resources | nindent 12 }}
