#!/usr/bin/env bash
set -euo pipefail

REPO="kushin77/self-hosted-runner"

echo "Generating deployment artifacts for ${REPO}"

STATUS_FILE=SECRETS_REMEDIATION_STATUS_MAR8_2026.md

cat > "$STATUS_FILE" <<'EOF'
# Secrets Remediation Status — autogenerated

**Deployed:**

- Orchestrator: .github/workflows/secrets-orchestrator-multi-layer.yml
- Health check: .github/workflows/secrets-health-multi-layer.yml
- Provisioning: .github/workflows/operator-automatic-provisioning.yml
- Auto-provision workflow: .github/workflows/deploy-cloud-credentials.yml

**Current Run:** autogenerated on deployment

EOF

echo "Status file written: $STATUS_FILE"

# Create or update high-level status issue (#1702 if exists)
ISSUE_TITLE="Secrets Orchestration: Multi-Layer Automation Deployed & Operational"

EXISTING=$(gh issue list --repo "$REPO" -s open -L 100 --json number,title --jq ".[] | select(.title==\"${ISSUE_TITLE}\") | .number" || true)

BODY="Autogenerated deployment artifacts updated. See $STATUS_FILE in repository."

if [ -n "$EXISTING" ]; then
  echo "Updating issue #$EXISTING"
  gh issue comment "$EXISTING" --repo "$REPO" --body "$BODY"
else
  echo "Creating issue: $ISSUE_TITLE"
  gh issue create --repo "$REPO" --title "$ISSUE_TITLE" --body "$BODY" --label "automation,operator-action" || true
fi

echo "Done."
