apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: canonical-secrets-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: canonical-secrets-api
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
