name: Verify Required Secrets
true:
  workflow_dispatch: null
  push:
    branches:
    - main
permissions:
  id-token: write
  contents: read
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Fetch Ephemeral Credentials
      uses: kushin77/get-ephemeral-credential@v1
      id: creds
      with:
        credential-names: 'GCP_PROJECT_ID

          '
        retrieve-from: auto
    - name: Validate
      run: "if [-z \"${{ steps.creds.outputs.GCP_PROJECT_ID }}\"]; then\n  echo \"\
        Critical: GCP_PROJECT_ID missing\"\n  exit 1\nfi\necho \"All required core\
        \ secrets present.\"\n"
    timeout-minutes: 30
    name: Verify
